export const TodoConstants = {
    GET_ALL_TODO_ITEM         : "GET_ALL_TODO_ITEM",
    GET_ALL_TODO_ITEM_SUCCESS : "GET_ALL_TODO_ITEM_SUCCESS",
    GET_ALL_TODO_ITEM_FAILURE : "GET_ALL_TODO_ITEM_FAILURE",

    POST_TODO_ITEM         : "POST_TODO_ITEM",
    POST_TODO_ITEM_SUCCESS : "POST_TODO_ITEM_SUCCESS",
    POST_TODO_ITEM_FAILURE : "POST_TODO_ITEM_FAILURE",

    EDIT_TODO_ITEM         : "EDIT_TODO_ITEM",
    EDIT_TODO_ITEM_SUCCESS : "EDIT_TODO_ITEM_SUCCESS",
    EDIT_TODO_ITEM_FAILURE : "EDIT_TODO_ITEM_FAILURE",
}

